
<?php
if($_GET['param']=="album")
    {
        include_once("album/list_public_albums.php");
        return;
    }
if($_GET['param']=="index")
    {
        include_once("include/register.php");
        return;
    }
    if($_GET['param']=="test")
    {
        include_once("include/test.php");
        return;
    }
    if($_GET['param']=="log_in")
    {
        include_once("login/login.php");
        return;
    }
    if($_GET['param']=="admin")
    {
        include_once("feature/helloadmin.php");
        return;
    }
    if($_GET['param']=="logout")
    {
        include_once("logout/logout.php");
        return;
    }
    if($_GET['param']=="department")
    {
        include_once("department/department.php");
        return;
    }
    if($_GET['param']=="country")
    {
        include_once("country/country.php");
        return;
    }
    else
    {
        include_once("register/register.php");
        return;
    }
?>